apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-simple-working
  namespace: elasticsearch
  labels:
    app: kibana-simple-working
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-simple-working
  template:
    metadata:
      labels:
        app: kibana-simple-working
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.5.1
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        # No health checks - let Kibana start naturally
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-working-config-fixed
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-simple-working
  namespace: elasticsearch
  labels:
    app: kibana-simple-working
spec:
  type: ClusterIP
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana-simple-working
