apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: elasticsearch
  labels:
    app: kibana-simple-working
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "5601"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/status"
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana-simple-working
---
# Security Group for Load Balancer (if needed)
# This would be applied via Terraform or AWS CLI
# aws ec2 create-security-group --group-name kibana-lb-sg --description "Kibana Load Balancer Security Group"
# aws ec2 authorize-security-group-ingress --group-name kibana-lb-sg --protocol tcp --port 5601 --cidr 0.0.0.0/0
