clusterName: "advanced-elastic-production-aws-elasticsearch"

replicas: 3

esConfig:
  elasticsearch.yml: |
    cluster.name: advanced-elastic-production-aws-elasticsearch
    discovery.seed_hosts: elasticsearch-master
    cluster.initial_master_nodes: elasticsearch-master-0
    xpack.security.enabled: true
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

secretName: "elasticsearch-credentials"

resources:
  limits:
    cpu: "2000m"
    memory: "8Gi"
  requests:
    cpu: "500m"
    memory: "8Gi"

volumeClaimTemplate:
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "100Gi"
    storageClassName: "gp3"