apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 80
    targetPort: 5601
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 80
    targetPort: 9200
    protocol: TCP
  type: LoadBalancer

