apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-minimal-config
  namespace: elasticsearch
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-service:9200"]
    
    # Disable security features
    xpack.security.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"
    xpack.reporting.encryptionKey: "something_at_least_32_characters_long"
    xpack.security.encryptionKey: "something_at_least_32_characters_long"
    
    # Disable cloud and subscription features
    xpack.cloud.enabled: false
    xpack.cloud.id: ""
    xpack.cloud.base_url: ""
    
    # Disable fleet and agent management
    xpack.fleet.enabled: false
    xpack.ingestManager.enabled: false
    xpack.fleet.registryUrl: ""
    xpack.fleet.agents.elasticsearch.host: "http://elasticsearch-service:9200"
    
    # Disable telemetry
    telemetry.enabled: false
    xpack.telemetry.enabled: false
    xpack.telemetry.banner: false
    
    # Disable problematic plugins
    xpack.cloudSecurityPosture.enabled: false
    xpack.cloudDefend.enabled: false
    xpack.cloudExperiments.enabled: false
    xpack.cloudIntegrations.enabled: false
    
    # Disable ML features
    xpack.ml.enabled: false
    
    # Disable watcher
    xpack.watcher.enabled: false
    
    # Disable graph
    xpack.graph.enabled: false
    
    # Disable reporting
    xpack.reporting.enabled: false
    
    # Disable canvas
    xpack.canvas.enabled: false
    
    # Disable maps
    xpack.maps.enabled: false
    
    # Disable uptime
    xpack.uptime.enabled: false
    
    # Disable APM
    xpack.apm.enabled: false
    
    # Disable infrastructure
    xpack.infra.enabled: false
    
    # Disable logs
    xpack.logs.enabled: false
    
    # Disable metrics
    xpack.metrics.enabled: false
    
    # Disable synthetics
    xpack.synthetics.enabled: false
    
    # Disable observability
    xpack.observability.enabled: false
    
    # Configure logging
    logging.appenders:
      console:
        type: console
        layout:
          type: pattern
          pattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
    logging.root:
      appenders: ["console"]
      level: "info"
    
    # Disable newsfeed
    newsfeed.enabled: false
    
    # Disable home
    xpack.home.enabled: false
