# Elasticsearch External Service (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
  namespace: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
