apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-light
  namespace: monitoring
  labels:
    app: grafana-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-light
  template:
    metadata:
      labels:
        app: grafana-light
    spec:
      nodeSelector:
        nodegroup: general
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-light
  namespace: monitoring
  labels:
    app: grafana-light
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana-light

