apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: elasticsearch
  labels:
    app: kibana-simple-working
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30561  # Custom node port (30000-32767 range)
    protocol: TCP
  selector:
    app: kibana-simple-working
---
# Optional: Ingress for cleaner URLs
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elasticsearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: kibana-staging.local  # You can change this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana-nodeport
            port:
              number: 5601
