# Elasticsearch Helm Chart Values - COMPLETELY DISABLE SECURITY
clusterName: "elasticsearch"
nodeGroup: "elasticsearch"

# Resource Configuration
resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: "1000m"
    memory: "2Gi"

# Java Options
esJavaOpts: "-Xms1g -Xmx1g"

# Replicas
replicas: 1

# Storage Configuration
volumeClaimTemplate:
  resources:
    requests:
      storage: 50Gi
  accessModes: ["ReadWriteOnce"]

# SECURITY COMPLETELY DISABLED - This is critical
xpack:
  security:
    enabled: false
    http:
      ssl:
        enabled: false
    transport:
      ssl:
        enabled: false

# Health Checks
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 20

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 90
  periodSeconds: 15

# Node Selector for EKS
nodeSelector:
  nodegroup: elasticsearch

# Tolerations
tolerations:
- effect: NoSchedule
  key: dedicated
  value: elasticsearch

# Service Configuration
service:
  type: ClusterIP
  port: 9200
