apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elasticsearch
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-service:9200"]
    xpack.security.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"
    xpack.reporting.encryptionKey: "something_at_least_32_characters_long"
    xpack.security.encryptionKey: "something_at_least_32_characters_long"
    # Disable external package registry
    xpack.fleet.registryUrl: ""
    xpack.fleet.agents.elasticsearch.host: "http://elasticsearch-service:9200"
    # Disable telemetry
    telemetry.enabled: false
    xpack.telemetry.enabled: false
    # Disable external integrations
    xpack.fleet.enabled: false
    xpack.ingestManager.enabled: false
    # Configure logging
    logging.appenders:
      console:
        type: console
        layout:
          type: pattern
          pattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
    logging.root:
      appenders: ["console"]
      level: "info"
