# Kibana Helm Chart Values
# This file configures the Kibana deployment for the CI/CD pipeline

# Kibana Configuration
elasticsearchHosts: "http://elasticsearch-master:9200"
kibanaIndex: ".kibana"

# Resource Configuration
resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

# Replicas
replicas: 1

# Service Configuration
service:
  type: ClusterIP
  port: 5601

# Ingress (disabled by default)
ingress:
  enabled: false

# Health Checks
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 20

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 15

# Node Options
nodeOptions: "--max-old-space-size=1800"

# Environment Variables
env:
  - name: SERVER_HOST
    value: "0.0.0.0"
  - name: SERVER_PORT
    value: "5601"
  - name: ELASTICSEARCH_HOSTS
    value: "http://elasticsearch-master:9200"
  - name: ELASTICSEARCH_USERNAME
    value: "elastic"
  - name: ELASTICSEARCH_PASSWORD
    value: "changeme"

# Security Configuration
xpack:
  security:
    enabled: false
    encryptionKey: "changeme"

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

# Pod Security Context
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000

# Container Security Context
containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
